server {
	listen 80;
	server_name _;
    # 连接上游服务器的超时时间（默认 60s）
    proxy_connect_timeout 10s;

    # 向上游服务器发送请求的超时（默认 60s）
    proxy_send_timeout 3600s;

    # 从上游服务器读取响应的超时（默认 60s）
    proxy_read_timeout 3600s;

    client_max_body_size 1000m;

    location /arp/ {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://openinsight-arp:33080/arp/;
    }

    location /api/ {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://openinsight-arp:33080/api/;
    }

    location /dmp/ {
        alias /app/dmp-admin/;
        index index.html index.htm;
        try_files $uri $uri/ /dmp/index.html;
    }

    location /doc.html {
        deny all;
    }
    location /webjars/ {
        deny all;
    }
    location /v3/ {
        deny all;
    }

    location /admin-api/ {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://openinsight-dmp-api:8090/admin-api/;
    }

    location /dmp/admin-api/ {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://openinsight-dmp-api:8090/admin-api/;
    }

    location /open-api/ {
              proxy_set_header X-Real-IP  $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://openinsight-dmp-api:8090/open-api/;
    }

    location /dmp/open-api/ {
              proxy_set_header X-Real-IP  $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://openinsight-dmp-api:8090/open-api/;
    }
}
